version: '3.8'


services:

  flow_scheduler:
    build: 
      context: .
      additional_contexts: 
        - flow_dir=${FLOW_DIR}
    image: flow_scheduler
    container_name: flow_scheduler
    env_file:
      - .env.local
    command: python setup.py
    environment:
      # Prefect
      - PREFECT_API_URL=${PREFECT_API_URL}
      # MLflow
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    networks:
      - mlops


networks:
  mlops:
    external: true